### ISSUE TITLE
改版小程序后是否可用

### ISSUE THREAD

**Issue by bybl6966** [jj4/antlinkercampus#1]
老哥你好，今天看到了这篇文章，想问一下现在校园集结号应用小程序后是否还能实现自动填报呢？感谢！

**Comment by jj4** [comment]
改版后，除开发者外，用户无法模拟通过小程序登录鉴权，故不可行。可参考[微信开放文档](https://developers.weixin.qq.com/miniprogram/dev/api/open-api/login/wx.login.html)

**Comment by bybl6966** [comment]
收到，感谢解答！
目前认为通过定时使用原有的ssid模拟访问可以保持ssid不失效，但存在登录冲突问题：一旦在重新打开小程序先前ssid就会失效
不知学长有没有其他研究呢
